name: CLI Tests

on: [push]

jobs:
  cli_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --editable .[test]
      - name: Download game data
        run: |
          mkdir cdda-game-data
          cd cdda-game-data
          git init
          git remote add -f origin https://github.com/CleverRaven/Cataclysm-DDA.git
          git config core.sparseCheckout true
          echo data/json/ >> .git/info/sparse-checkout
          git pull --depth 1 origin master
          git checkout master
          ls
          cd ..
