name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --editable .[test]
          pip install pytest
      - name: Test with pytest
        run: |
          pytest --cov cdda_tools --cov-report term-missing --cov-report xml:coverage.xml -v

  badge:
    runs-on: ubuntu-latest
    needs: [tests]
    #if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: action-badges/create-orphan-branch@0.1.0
        with:
          branch-name: badges
      - name: Make Coverage Badge
        uses: action-badges/cobertura-coverage-xml-badges@0.2.1
        with:
          file-name: coverage.svg
          badge-branch: badges
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          coverage-file-name: ./coverage.xml
