name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --editable .[test]
          pip install pytest black 'pylint<3' 'isort[colors]<6'
      - name: Test with pytest
        run: |
          pytest
      - name: Lint with black
        run: |
          black --check --diff --color .
      - name: Lint with isort
        run: |
          isort --check --diff --color .
#      - name: Lint with pylint
#        run: |
#          pylint src/cdda_tools
